### ISSUE TITLE
Simulation Tab for Testing

### ISSUE THREAD

**Issue by robinku07** [MutonUfoAI/pgina#101]
1. Is there any specific reason to remove the simulation tab from Pgina User Interface?
2. Can we keep the Configuration UI user friendly or is there any specific reason to remove groups checking from authentication and Authorization Tabs?

**Comment by MutonUfoAI** [comment]
1) There are more than one, but to keep it simple. There is now way to simulate a login in the same way as windows would log you in. It will always end up in a mess.
2) I don't know what you are talking about
