### ISSUE TITLE
Authenticate local users

### ISSUE THREAD

**Issue by bilBob430** [MutonUfoAI/pgina#104]
Hi,
I'd like to authenticate users that were not created by pGina with plugins, is it possible? 

I know the doc specify they need to be marked as "pGina created" (saw the code in the local machine plugin), can't I just remove the checks/mark them as pGina created to be able to do so ? 

Thanks for your time

**Comment by MutonUfoAI** [comment]
There is a fork that has done that
https://github.com/momiji/pgina/commits/master
Mess around with the logon process and get all kinds of results.

**Comment by bilBob430** [comment]
Nice ! It does exactly what I needed, thanks for your work on this fork by the way !
