### ISSUE TITLE
Same user (Workgroup + AD)

### ISSUE THREAD

**Issue by subu1979** [MutonUfoAI/pgina#130]
Hi,
I have same username in local (Workgroup) and Windows AD, when i logged on using Credential provider, iam able to authenticate only to local user not to AD ?

Note:- This scenario is only when both local and AD users are identical.

Need your help.
Thanks & Regards
KMV.Subramanyam

**Comment by MutonUfoAI** [comment]
Take a look at https://github.com/MutonUfoAI/pgina/issues/70

**Comment by subu1979** [comment]
Hi,

Thanks for your reply. 

I have downloaded the Latest version and tested with both local and AD User. 

Regards
KMV.Subramanyam
