### ISSUE TITLE
Install and configure via command line

### ISSUE THREAD

**Issue by dioubernardo** [MutonUfoAI/pgina#131]
Hello I'm creating an installation package in my institution and would need to install and configure pGina without user interactions.

For silent installation I'm using
pGinaSetup.exe / silent / norestart
is working right.

To try to load settings, I installed on a computer to make the settings via pGina.Configuration.exe and I used regedit.exe to export pgina.reg.

I imported the same computer and it worked, but when I reinstalled windows and tried to import it did not work.

To import regedit / s pgina.reg

**Comment by MutonUfoAI** [comment]
take a look at
https://github.com/MutonUfoAI/pgina/issues/60
https://github.com/MutonUfoAI/pgina/issues/68

**Comment by dioubernardo** [comment]
Ok, my mistake, I was exporting and importing the entire node settings.

I just created a .reg with the items I'd like to change and it's working.
