### ISSUE TITLE
Windows 10 - No pGina login screen

### ISSUE THREAD

**Issue by Speirs47** [MutonUfoAI/pgina#139]
I've just installed pGina fork instead of the original one and I can't get it to work. I configured LDAP and there's just no pGina in login screen.

Also, it's a pity there's no simulator anymore. On original pGina I had a problem with SSL connection that's why I switched to pGina fork hoping it was some kind of bug but now I have no way to test it.

**Comment by MutonUfoAI** [comment]
https://github.com/MutonUfoAI/pgina/issues/62
and the rest is very helpful.
What version of windows 10 are you using
Is the service running
What have you configured
Have you set a provider filter ....
http://mutonufoai.github.io/pgina/documentation/user.html#credential_provider_filter

**Comment by Speirs47** [comment]
1. Version is Windows 10 Pro 1809 compilation 17763.316

2. Turns out service is set to start automatically but it doesn't start on reboot.
Here's log from pGina.Service.ServiceHost_log after rebooting

> 2019-03-04 08:54:28,521 [8156|7|INFO ] pGina.Service.Impl: SessionChange:1 6
> 2019-03-04 08:54:28,597 [8156|42|INFO ] pGina.Service.Impl: SessionChange: 1 -> SessionLogoff
> 2019-03-04 08:54:28,613 [8156|42|INFO ] pGina.Service.Impl: Logoff in progress 1
> 2019-03-04 08:54:28,661 [8156|42|INFO ] pGina.Service.Impl: CREDUIhelper:(1)
> 2019-03-04 08:54:28,722 [8156|42|INFO ] pGina.Service.Impl: User:? in session:1 is unknown to pGina
> 2019-03-04 08:54:28,862 [8156|42|INFO ] pGina.Service.Impl: Logoff completed 1
> 2019-03-04 08:54:29,613 [8156|45|INFO ] Pgina Service: Preshutdown Event received
> 2019-03-04 08:54:29,628 [8156|45|INFO ] Pgina Service: RequestAdditionalTime finished
> 2019-03-04 08:54:29,801 [8156|45|INFO ] pGina.Service.Impl: Stopping service
> 2019-03-04 08:54:29,801 [8156|45|DEBUG] SessionLimitPlugin: Stopping timer

3. I configured LDAP to Authenticate, Authorize and as Gateway. No filters in Authorization (default Allow), 
in Gateway Users should be always added to Users group.
Local machine is checked for Authentication and Gateway.

4. I didn't set that before but when I set it today it didn't change anything.

I guess the problem is with the service not starting but I don't understand why it's not starting. I will try to set it to start automatically (delayed) before you respond me. If I won't edit my post in like 10 minutes then it means that it didn't help either.

**Comment by Speirs47** [comment]
I noticed there is no pGinaCredentialProvider.dll in x64 directory (there is one in Win32 though). Not sure if that matters but I reinstalled pGina and the file appeared and now I get the pGina login screen.

So this issue may be closed.

**Comment by Speirs47** [comment]
FYI, for some reason this file keeps disappearing
