### ISSUE TITLE
local admin password scrambled via RDC

### ISSUE THREAD

**Issue by rolltack** [MutonUfoAI/pgina#15]
Hi, 
I can reproduce the following problem: When I log in via RDC into my local admin account, the password is scrambled. I need to log physically into the machine and reset the PW via my back-up admin profile.

On that machine RDC is set to allow connction only with NLA.

The only local profiles are admin accounts, every other account is authenticated via LDP running on a Synology NAS.

Pgina fork 3.2.4.1 settings:
plugins:
- LDAP and local machine authentication
- local machine gateway
- LDAP change password

local machine gateway settings:
-Ticks on "failure to create...", "Scramble password..", "Only scramble when....".
- Never scramble for all admin accounts
- Mandatory groups: Remote Desktop Users

Let me know if you need any additional info. 

Great work by the way (despite my problem). Big fan of pGina and fork.

**Comment by MutonUfoAI** [comment]
I'm tracking users by there Description "pGina created".
As long as those admin users dont own this mark, they aren't touched.
You'll see informations related to this in the pgina log (%ProgramFiles%\pGina\log\pGina.Service.ServiceHost_log.txt)
scramble password %username%
not scramble password %username%

**Comment by MutonUfoAI** [comment]
.) can't reproduce
.) no respond
.) closed
