### ISSUE TITLE
pGina service is not shutting down

### ISSUE THREAD

**Issue by maheshmadhyastha7** [MutonUfoAI/pgina#156]
Hi,
I am facing this when I restart the machine , the windows shows the pgina service is shutting down which will never happen. I have to revert the force stop it.
Can anyone help pls?I am using pgina fork 3.9.9.12
![pgina issue](https://user-images.githubusercontent.com/12908773/74401852-8e494600-4e48-11ea-8c09-df64963558e5.JPG)

**Comment by MutonUfoAI** [comment]
There is a log file located
%ProgramFiles%\pGina.fork\log\pGina.Service.ServiceHost_log.txt

Pgina wan't shut down until all users are logged off.
Pgina is doing the logoff process in the background, even if it seems so that you are already logged off, you are most likely not.

**Comment by maheshmadhyastha7** [comment]
I cannot locate the log files because I am VM of Windows Server 2016. I have to revert back snapshot in order to start all over again. And the message 'Shutting down service: pGina service' never completes.
Also, I dont have any logged in users in the VM except admin who can only restart the machine.

**Comment by MutonUfoAI** [comment]
Just mount the VM diskimage in Windows and get the log .....

**Comment by maheshmadhyastha7** [comment]
M not able to mount that since its not .iso file , its ovf.

**Comment by maheshmadhyastha7** [comment]
It was problem with Session change handler. I was getting Object reference error during remote session disconnect. Figured out.
