### ISSUE TITLE
LDAP GroupAuthzRules doesn't read after saving to registry

### ISSUE THREAD

**Issue by vladimirmartsul** [MutonUfoAI/pgina#16]
Hello!

I'm trying to setup simple rule in Authorization tab of LDAP plugin. I want to allow access only if user is a member of "cn=! All users,ou=Groups,ou=Structure,dc=example,dc=com"
![1311](https://cloud.githubusercontent.com/assets/2290081/7713402/53dc536c-fe99-11e4-9435-069e124f6208.png)

After this I click Save and open this window again but doesn't see saved rule
![1312](https://cloud.githubusercontent.com/assets/2290081/7713431/8eff6a06-fe99-11e4-91de-57474e3897fb.png)

There is rule still in registry
![1313](https://cloud.githubusercontent.com/assets/2290081/7713461/b3ac846a-fe99-11e4-9763-6634a49892b4.png)

When I simulate login I get deny error and this string in log:
```
LDAP GroupRuleLoader: Unrecognized registry entry when loading authorization rule, ignoring: 0	0	cn=! All users,ou=Groups,ou=Structure,dc=example,dc=com	(member=%u)	1
```

**Comment by vladimirmartsul** [comment]
I use pgina 3.2.4.1 (your fork) with Windows Server 2012 R2 Standard (x64)

**Comment by MutonUfoAI** [comment]
The regkey is not compatible
delete the key and apply your rule again

**Comment by vladimirmartsul** [comment]
Yes, I was trying this and without luck. Also I trying to remove all pgina3 registry section and with no luck too.
Finally I get strange permanent error about stream pipe bla-bla-bla and to revert back to original pginaon my KVM server. But additionally I test pgina-fork on vmware VM with the same OS config and get no error about stream.

**Comment by MutonUfoAI** [comment]
I dont know what you have done exactly to get the "stream pipe bla-bla-bla" error
but the "Unrecognized registry entry" error is a bug

**Comment by rahele** [comment]
i have the same problem on  pgina 3.2.4.1 (fork).
any idea about solving this problem?

**Comment by MutonUfoAI** [comment]
a new version will soon be released

**Comment by rahele** [comment]
thanks for your answer MutonUfoAI!
when the new version  will be released? 
because i really need it
and is there another way to handle this problem?

**Comment by MutonUfoAI** [comment]
add fix 636ccaec08d3d3683d6954834bdd9b72226c00c8

https://github.com/MutonUfoAI/pgina/releases/download/untagged-726292478fd81edb4313/pGinaSetup-3.2.4.2.exe

**Comment by rahele** [comment]
i made all these changes, build the project and replaced the "pGina.Plugin.Ldap.dll" with the old one. only LDAP plugin disappeared from the Pgina fork, nothing else.
May you help me with it?

**Comment by mangokingTW** [comment]
Excuse me.
Why do the version 3.2.4.1 or later disappear?
I am facing the same problem.
Thank you in advance!

**Comment by MutonUfoAI** [comment]
possibly you copied it into the wrong folder
or a compiler issue
net 4.5 instead of 4.0

open the pgina log and search 4
PluginLoader: Initializing
there you see whats going on ...

**Comment by MutonUfoAI** [comment]
A new build is available
https://github.com/MutonUfoAI/pgina/releases
