### ISSUE TITLE
Ldap and Groups. Windows 8.1

### ISSUE THREAD

**Issue by douglasanpa** [MutonUfoAI/pgina#18]
Hello, I tested on my windows 8.1 and everything worked perfectly, except the addition of the user groups, the simulation says it will add ordinary users to S-1-5-32-545 group and administrators to "S-1 5-32-545 "and" S-1-5-32-544 ", however, users are not in any group.

Some additions that I think would be welcome:

* Ability to edit the rules;
* By clicking save if you happen to have something in the area of add rules that warn not added or automatically add before saving.

Version: 3.2.4.1

**Comment by MutonUfoAI** [comment]
please do not use the simulator
ill remove it in the next release but 4 now please ignore it

I think that the option "Always authenticate local users" is your problem
deselect it!
The Local machine plugin will not run the gateway stage if the user is already on the system
I know its irritating but already fixed 4 the next release
