### ISSUE TITLE
Add firstlogin action

### ISSUE THREAD

**Issue by Yamakasi** [MutonUfoAI/pgina#25]
It would be nice if a person logs in for the first time, or we can set such thing as administrator when we want to, that we can perform an batch or exec, or whatever.

For an example, redirecting to a webpage or a help page.

**Comment by MutonUfoAI** [comment]
I've created a scripting plugin
https://github.com/MutonUfoAI/pgina/commit/7501c82c8dd42b811a057f5358236ac263b3111e
at any stage you can now run a script in system context
or in notify and password change scenario in context of the user
