### ISSUE TITLE
LDAP GroupAuthzRules and groupGatewayRules doesn't read after saving to registry

### ISSUE THREAD

**Issue by rahele** [MutonUfoAI/pgina#27]
Hello
I'm trying to setup simple rule in Authorization and Gateway tab of LDAP plugin. then i click on save and then apply.
when i check the registry file, the data is written on it. but there is no rule in the LDAP plugin in PGINA. and rules are not used when i try to log in.
any idea about this problem?

**Comment by MutonUfoAI** [comment]
duplicate of
https://github.com/MutonUfoAI/pgina/issues/16
