### ISSUE TITLE
Windows 10 compatibility

### ISSUE THREAD

**Issue by piejanssens** [MutonUfoAI/pgina#28]
Glad to see there is someone maintaining pGina!
In the main repo's master branch there are known issues for Win 10: https://github.com/pgina/pgina/issues/266 How about this fork?

**Comment by MutonUfoAI** [comment]
The fork is a bit different from pgina
but ive tested it on win10 using LDAP pgSMB2 and LocalMachine without much problems
whats in my master of course

Let me say this
I have Win10 on my radar
but dont expect a release before April
I have to do a lot of tests .....

**Comment by piejanssens** [comment]
Cool - let's leave this open to track the status and to know when win 10 is supported fully.

**Comment by soleroitsolutionsltd** [comment]
Just realized that this is where the action is now... :)
Anything I can do to help with Win10 compatibility ?

**Comment by MutonUfoAI** [comment]
During tests i was able to reproduce an old bug
"Pipe is Broken"

https://github.com/MutonUfoAI/pgina/blob/7501c82c8dd42b811a057f5358236ac263b3111e/pGina/src/Abstractions/Pipes/PipeServer.cs#L158
throws
Exception "Pipe is Broken"

its from
https://github.com/MutonUfoAI/pgina/blob/7501c82c8dd42b811a057f5358236ac263b3111e/pGina/src/Abstractions/Pipes/Pipe.cs#L78
https://github.com/MutonUfoAI/pgina/blob/7501c82c8dd42b811a057f5358236ac263b3111e/pGina/src/Abstractions/Pipes/Pipe.cs#L90

The longer
https://github.com/MutonUfoAI/pgina/blob/7501c82c8dd42b811a057f5358236ac263b3111e/pGina/src/Abstractions/Pipes/Pipe.cs#L75
is waiting for completion (deeeeeply in there the whole login process is taking place)
the more likely a "Pipe is Broken" exception is thrown

This is a blocker!

**Comment by MutonUfoAI** [comment]
This bug still exists, but only occur in CRED_UI events.
A user may not get an error message, thats the worst than can happen.
The new build https://github.com/MutonUfoAI/pgina/releases will send an email if it occurs.

**Comment by chunkychode** [comment]
@MutonUfoAI  was there anything special you had to do to have windows 10 even present an option to login with the master branch ( as of today ) ?
built installed and configured just fine, just cant see it :/

**Comment by MutonUfoAI** [comment]
Have you build a 64bit version too.

**Comment by hamlet1601** [comment]
Try to install Microsoft Visual C++ 2012 Redistributable, this works for me, and now I can see pGina login.

**Comment by esaeberg** [comment]
Hi

I use pGina (official) since this spring on a VM with Win10 Pro with an access with RDC and a synology server

My problem is every months, it's said "the password is expired" but I don't have any expired rules on synology ldap directory! 

For fix that I have to:

1/ change password in ldap synology (even by the same)
2/ go on the consol of ESXi for connect with the new password
3/ go on the admin for autorise again this user to use RDC (I do not understand why this setting is deleted by windows)

And after that I can again use the user in RDC ...

Your fork will work better ?

**Comment by MutonUfoAI** [comment]
I dont own a synology  nas ....
