### ISSUE TITLE
Use original username to unlock computer

### ISSUE THREAD

**Issue by hamlet1601** [MutonUfoAI/pgina#29]
Hello,

In the latest pGina stable version (3.1.8.0, not fork version) after login with LDAP user, redirecting it to a local user with the Single User Login plugin,  with "General > Unlock > Use original username to unlock computer (Windows 7 and later)" option it was possible to unlock computer with the LDAP user logged password. In the pGina fork this is not possible. Trying to unlock, pGina reports an error of user unknown or incorrect password and it's not possible to unlock session.

Would it be possible to make this option work properly in pGina fork?

Thank you.

**Comment by MutonUfoAI** [comment]
i need a log file

**Comment by hamlet1601** [comment]
Hi, this is my log file.

[pGina.Service.ServiceHost_log.txt](https://github.com/MutonUfoAI/pgina/files/173679/pGina.Service.ServiceHost_log.txt)

**Comment by MutonUfoAI** [comment]
I've found the code of problem
but im working on another part of pgina
Ill fix it as soon as possible ...

**Comment by hamlet1601** [comment]
Thank you, I appreciate your help.

**Comment by MutonUfoAI** [comment]
fixed
https://github.com/MutonUfoAI/pgina/releases

**Comment by hamlet1601** [comment]
It seems to work, but now unlocks the session even if the password is incorrect.

I attached my log file.

[pGina.Service.ServiceHost_log.txt](https://github.com/MutonUfoAI/pgina/files/197730/pGina.Service.ServiceHost_log.txt)

**Comment by hamlet1601** [comment]
Thank you for your work, now it works fine!
