### ISSUE TITLE
After uninstallation of pgina.fork no login possible anymore - BAD!

### ISSUE THREAD

**Issue by sbogun** [MutonUfoAI/pgina#36]
Hi,

it seems that the pgina.fork uninstaller doesn't completely uninstall pgina.fork. Now after having it uninstalled from my windows 2012R2 server (using the provided uninstaller), no login is possible anymore as the systems appears to be waiting to for the pGina service (which doesn't exist anymore), see screenshot.
![screen shot 2016-06-13 at 12 00 54](https://cloud.githubusercontent.com/assets/9930951/16003750/807c61b6-315e-11e6-85b9-bc0c6702f113.png)

![screen shot 2016-06-13 at 12 02 13](https://cloud.githubusercontent.com/assets/9930951/16003780/b243885a-315e-11e6-8c92-22077db138f4.png)

Reboot doesn't help as opposed to what the 2nd screenshot tells.

BAD! What can I do?

**Comment by MutonUfoAI** [comment]
I'll fix that ....

**Comment by MutonUfoAI** [comment]
3.9.9.3 doesn't show this problem......
