### ISSUE TITLE
Empty Password

### ISSUE THREAD

**Issue by soulstyless** [MutonUfoAI/pgina#37]
How in your fork  enable empty password?
In original i do this (Credential::GetSerialization )
`PWSTR username = m_loginResult.Username().length() > 0 ? _wcsdup(m_loginResult.Username().c_str()) : NULL;
			//disable empty passwrd
			//PWSTR password = m_loginResult.Password().length() > 0 ? _wcsdup(m_loginResult.Password().c_str()) : NULL;
			//enable empty password
			PWSTR password = _wcsdup(m_loginResult.Password().c_str());
			PWSTR domain   = m_loginResult.Domain().length()   > 0 ? _wcsdup(m_loginResult.Domain().c_str())   : NULL;`

But in your fork this not work.
If in Provider::GetSerializedCredentials do this
`if (password)
			{
				if (SerializedPasswordAvailable())
				{
					*password = (PWSTR) LocalAlloc(LMEM_ZEROINIT, m_setSerialization->Logon.Password.Length + sizeof(wchar_t));
					CopyMemory(*password, m_setSerialization->Logon.Password.Buffer, m_setSerialization->Logon.Password.Length);
				}
				else
				{
					pDEBUG(L"SerializedPasswordAvailable false");
						//*password = NULL;
				}}`

All work, but password field have one default char

**Comment by MutonUfoAI** [comment]
Take a look into the eventlog (application) you'll see that logonui.exe has crashed.

My early guess was the null pointer is causing some problems here and ....
if you fix lines
https://github.com/MutonUfoAI/pgina/blob/2d6f69fb7a7055c729ba136d9576f56686d8ff6f/pGina/src/CredentialProvider/Credential.cpp#L695
and
https://github.com/MutonUfoAI/pgina/blob/2d6f69fb7a7055c729ba136d9576f56686d8ff6f/pGina/src/CredentialProvider/Credential.cpp#L528

by replacing
password
by
(password)? password : L""
pgina CP wont crash any longer

tested it with logon and unlock
havent tried anything else ...
