### ISSUE TITLE
LDAP configuration on different version

### ISSUE THREAD

**Issue by abdlquadri** [MutonUfoAI/pgina#39]
Hello Guys,

I have been trying to solve an issue I have with admin permissions. I found a documentation where I can add a rule to ad users to admin groups.

But on some PGINA versions the configuration dialog is different.

My question is how can I fill in the boxes for the new PGINA versions for it to have the same effect.

I have attached a screenshot of the one I filled correctly, kindly guide me fill in the other screenshot.

Thank You.
![ldap_config_pgina](https://cloud.githubusercontent.com/assets/594308/19084217/82feb990-8a5d-11e6-9c06-21c780b619d9.PNG)
![ldap_config_pgina_2](https://cloud.githubusercontent.com/assets/594308/19084220/8a02e5c2-8a5d-11e6-8459-b0662d15ab24.PNG)

**Comment by MutonUfoAI** [comment]
http://mutonufoai.github.io/pgina/documentation/plugins/ldap.html

**Comment by abdlquadri** [comment]
Yeah Thanks a lot.
