### ISSUE TITLE
Is there a compiled package for  3.9.9.4

### ISSUE THREAD

**Issue by mmiscool** [MutonUfoAI/pgina#40]

**Comment by MutonUfoAI** [comment]
https://github.com/MutonUfoAI/pgina/releases

**Comment by mmiscool** [comment]
Thanks
Might be nice to put this on the download page here
http://mutonufoai.github.io/pgina/download.html

**Comment by MutonUfoAI** [comment]
Its on my list

**Comment by MutonUfoAI** [comment]
done
