### ISSUE TITLE
Logon process without check for an account 

### ISSUE THREAD

**Issue by BRUCH05** [MutonUfoAI/pgina#43]
Hello,

I'm in trouble with just one account.

When i log with the account pdasprez, the plugin sequence is OK. The Deny check runs correctly by the ldap pluging.

2016-12-09 22:46:31,670 [1232|25|DEBUG] LdapPlugin: User pdasprez is (&(shadowExpire=1)) uid=pdasprez,cn=users,dc=ldap,dc=nas,dc=brugel

When i log with the account cbrugel, there isn't plugin sequence and the login is accepted with Windows credential.

2016-12-09 22:56:12,269 [1232|27|DEBUG] pGina.Service.Impl: Processing LoginRequest for: cbrugel in session: 12 reason: Login

With cbrugel account, the LDAP plugin seems to be not called.

Thanks by advance for your help.
Christophe (France - Paris - Homeless Association)

[pGina.Service.ServiceHost_log.txt](https://github.com/MutonUfoAI/pgina/files/643296/pGina.Service.ServiceHost_log.txt)

**Comment by MutonUfoAI** [comment]
pGina.fork triggers plugins only on pGina users.
Users are tracked by there profile description "pGina created".
cbrugel is a local users not created by pGina.fork
