### ISSUE TITLE
LDAP Plugin nested Group Membership

### ISSUE THREAD

**Issue by Tr0bs0r** [MutonUfoAI/pgina#44]
Hello,

is there a way to add AD-Users to local groups, when the group is nested in another group?
For example, we have User1, Group1 and Group2.
User1 is a member of Group1. Group2 only gets other groups as members. Now we want that if Group1 is a member of Group2, all members of Group1 should be added to the local Administrators group.
How can I realize this with pgina fork?

**Comment by MutonUfoAI** [comment]
most likely
but you need to create a more complex ldap query
https://technet.microsoft.com/en-us/library/aa996205%28v=exchg.65%29.aspx

**Comment by Tr0bs0r** [comment]
Thanks for your reply.
I solved my problem with the following query:

(&(objectCategory=Person)(sAMAccountName=%u)(memberOf:1.2.840.113556.1.4.1941:=cn=Group2,ou=TestOU,dc=example,dc=com))

With the matching rule object identifier "1.2.840.113556.1.4.1941" the query will look up the ancestry of the object Group2 till it finds (or possibly not) the correct user.
Further information: https://msdn.microsoft.com/en-us/library/aa746475(v=vs.85).aspx
