### ISSUE TITLE
Login Issue: E-Mail recognized as domain

### ISSUE THREAD

**Issue by Tr0bs0r** [MutonUfoAI/pgina#45]
Hello,

I have a second question. Our customers login is their mail address. Till now we have worked only with version 3.2.4.1 so this was not a problem. But we decided to switch to the latest (stable?) release 3.9.9.4. Now the part behind the "@" is recognized as the domain. We need the complete mail address for our login procedure. 
How can we deactivate the, for us, wrong recognition of the part behind the "@"?

Thank you very much and merry christmas!

**Comment by MutonUfoAI** [comment]
Yes this is an expected behavior.
pGina does now include AD support ....
.... i need to take a look into it .... how to decide if domain or mail

**Comment by MutonUfoAI** [comment]
fixed
https://github.com/MutonUfoAI/pgina/commit/8fc821b7e87a6e4d5d2e16a142f6ccb2a80b09b4

**Comment by Tr0bs0r** [comment]
The fix is working very well! Thanks and have a nice day! :) 👍
