### ISSUE TITLE
Space in login name

### ISSUE THREAD

**Issue by BRUCH05** [MutonUfoAI/pgina#46]
Hello,

I think i've found a little bug.

Ldap account : admin 
Ldap group : administrator (mapped to local administrator group)

1°) Login with "admin" account create a local account name "admin" with admin privilèges : OK
2°) Login with " admin" account (with a space before admin) create a local account name " admin" with admin privilèges : OK
So, i've two differents admin accounts created locally, one without space and one with a space in front of account name. 

The pgina.fork should be delete all space before using entered login name to avoid this behavior.

Best regards & Happy Christmas
Christophe

'

**Comment by MutonUfoAI** [comment]
A space in front is legit.
If you want to strip it, use the Modify Username Plugin.
Set it to Authentication
RegEx Replace
^\s+|\s+$
and make sure the Modify Username Plugin is the first plugin during Authentication in Plugin Order.

**Comment by BRUCH05** [comment]
Thank You so much,

The solution runs well !

Best regards.
