### ISSUE TITLE
Password Expired - Login Authorized - No password change requested

### ISSUE THREAD

**Issue by BRUCH05** [MutonUfoAI/pgina#47]
Hello,

I use the Directory Service from Synology to authenticate user.
I've enabled the password expiration feature. 

So when the password is expired, the login continues to be authorized, the Lanman connection to a drive are refused with the windows message "The user password is expired".

Is it possible in this case to call the change password windows to force the user to change the password ?

Thank you for your help. You make a very good job :-)
Christophe

**Comment by MutonUfoAI** [comment]
It depends, I dont know Synology.
The code 4 samba and AD is here
https://github.com/MutonUfoAI/pgina/blob/master/Plugins/LdapPlugin/Ldap/LdapServer.cs#L546

**Comment by BRUCH05** [comment]
Hello,

The directory service is a LDAP Server.

I would like to display the windows change password on the laptop when the ldap account is expired.
Is it possible to implement this behavior ?

Thanks in advance
Christophe
