### ISSUE TITLE
Pgina System.Runtime.Interop Services.COMException (0x80070035

### ISSUE THREAD

**Issue by shidevil** [MutonUfoAI/pgina#49]
Dear all,

I am having trouble trying to setup pgina on windows 2008 Server R2. The windows 2008 Server is harden and require admin privileged for most stuffs. The "Server" Services is ON and running.

The error is shown below as fail to process gateway: Unable to sync user local group membership: System.Runtime.Interop Services.COMException (0x80070035). The network path was not found.

In the pgina plugin, under local machine, the only checkbox checked is "Failure to create or join local groups should prevent login". The order of plugin was LDAP then Local machine. 

Radius and LDAP authentication and authorization are working. Except Local machine which throws a system.runtime.interop error.

Hope anyone who encountered this problem is able to resolve this issue.
![pgina1](https://cloud.githubusercontent.com/assets/5009021/22101929/6960728c-de70-11e6-93b3-080becc0b9d4.jpg)
![pgina2](https://cloud.githubusercontent.com/assets/5009021/22101933/6c3efbb8-de70-11e6-89ee-e1bae97247a5.jpg)
![local_machine_config](https://cloud.githubusercontent.com/assets/5009021/22101939/73c5c704-de70-11e6-8096-d56f6c202d28.png)

**Comment by MutonUfoAI** [comment]
You should ask this there
https://github.com/pgina/pgina/issues
