### ISSUE TITLE
Unexpected error while syncing user's info

### ISSUE THREAD

**Issue by jeroenmoors** [MutonUfoAI/pgina#52]
Hi,

I'm trying to get pGina working on a Windows 2012 server, using LDAP as a authentication backend and the LocalUser plugin to create user accounts that don't exist yet.

I've been struggeling for a few days now, but after tweaking some setting to get logins from RDP working, I get the error attached. ![error](https://cloud.githubusercontent.com/assets/1665245/22821832/1cbd5364-ef7d-11e6-822b-9f9c1a20b3a5.png)

The log file for this session is also attached.
[pGina.Service.ServiceHost_log.txt](https://github.com/MutonUfoAI/pgina/files/766278/pGina.Service.ServiceHost_log.txt)

Did I configured something wrong? Or is this a bug?

Thank you for feedback!

Jeroen

**Comment by MutonUfoAI** [comment]
The Server password policy is denying your user password.

**Comment by jeroenmoors** [comment]
It works!

Thank you so much!!
