### ISSUE TITLE
Modify username plugin not working

### ISSUE THREAD

**Issue by thakala** [MutonUfoAI/pgina#54]
I have been using modify username plugin since pGina 3.2.0.0. Since we moved to Windows Server 2016 I had to upgrade pGina to 3.2.4.1, on this version modify username plugin is still working fine. I am experiencing some RDP login issues with 3.2.4.1 so I decided to test pGina 3.9.9.7, unfortunately it seems that modify username plugin is no longer working on this version.

My configuration is to truncate user entered username and replace it with "administrator", 3.9.9.7 does not replace username before validating credentials as I get error that user entered username is not existing on target domain.

**Comment by MutonUfoAI** [comment]
pGina does now support domain logins
you need to tell pgina that you want to logon locally by typing
.\%Username%
