### ISSUE TITLE
Is it possible to implement scenario with NFC cards login?

### ISSUE THREAD

**Issue by xperiandri** [MutonUfoAI/pgina#56]
When PC is idle - screensaver plays (i.e. video or static picture)
When card is put onto the reader user info is retrieved from server and displayed. If user has enough balance a button to login is displayed.
When user takes card from the reader PC is locked. After 10 minutes without unlock user is signed off and screensaver is played.

**Comment by MutonUfoAI** [comment]
I simply don't know.
