### ISSUE TITLE
ICredentialProviderCredential2

### ISSUE THREAD

**Issue by xperiandri** [MutonUfoAI/pgina#57]
Is there any benefit to implement [ICredentialProviderCredential2](https://msdn.microsoft.com/en-us/library/windows/desktop/hh706912(v=vs.85).aspx) for pGina?

Is I understand the ability to retrieve a user SID was introduced to switch background of logon UI and lock screen with regard to user preferences.

Can this customizations be provided by pGina?

**Comment by MutonUfoAI** [comment]
Sure, but i will not do it.
It's open source, feel free to implement it....
