### ISSUE TITLE
LDAP Macro for DN of the user trying to log in?

### ISSUE THREAD

**Issue by sonicnkt** [MutonUfoAI/pgina#59]
Hey,
Im currently testing pgina fork with the ldap plugin to use in our organisation.
There is a central ldap server and i got basic authentication working relatively quickly.

No i want to modify the authentication stage a little bit to only allow users that are in our ou or are added to a special group.  And also grant admin rights in the gateway stage to certain users that are member of a admin group.

Groups on our ldap server have the "member" attribute that contains the full dn of a user, not just uid.

Attribute | Value
---|---
member | cn=abc123,ou=AB,ou=CD,o=Company

And as far as i understand i cant use wildcards while search for this attribute.
How can i check now if a user is in a certain group?  Is there a macro variable that holds the whole dn of the user trying to log in? 
```
!If (&(member=%D) in Base in "cn=admins,ou=Groups,ou=CD,o=Comapny" deny.
%D == Full DN ( cn=abc123,ou=AB,ou=CD,o=Company )
```

Thanks

**Comment by MutonUfoAI** [comment]
https://github.com/MutonUfoAI/pgina/issues/44

**Comment by sonicnkt** [comment]
Thanks that pushed me in the right direction :)
Dont check the group if the user is a member but look at the member and see if he is part of a certain group!
