### ISSUE TITLE
Export registry settings for pGina config for mass distribution

### ISSUE THREAD

**Issue by SHLelieveld** [MutonUfoAI/pgina#60]
Hello,

What registry entries do I need to export to create a x.reg file to use in mass distribution on installation/upgrade in our company?

Thanks,

Regards,

**Comment by MutonUfoAI** [comment]
the main pgina key
HKEY_LOCAL_MACHINE\SOFTWARE\pGina3.fork

and the plugins
HKEY_LOCAL_MACHINE\SOFTWARE\pGina3.fork\Plugins\GUID

dont export encrypted stuff like
HKEY_LOCAL_MACHINE\SOFTWARE\pGina3.fork\Plugins\0f52390b-c781-43ae-bd62-553c77fa4cf7
SearchPW
or
HKEY_LOCAL_MACHINE\SOFTWARE\pGina3.fork
notify_pass

If you need encrypted keys use
C:\Program Files\pGina.fork\encryptsetting.exe
