### ISSUE TITLE
LDAP plugin rules not saved

### ISSUE THREAD

**Issue by TobiasLogiline** [MutonUfoAI/pgina#65]
I cannot save rules for Authorization and Gateway.

After save and reopen configuration the rules are gone.

**Comment by MutonUfoAI** [comment]
%ProgramFiles%\pGina.fork\log\pGina.Configuration_log.txt

**Comment by TobiasLogiline** [comment]
The group I entered does not exist. So there was an execption in the log.
Thanks for the help. But an error message would be nice ...

**Comment by MutonUfoAI** [comment]
done
