### ISSUE TITLE
Error plugin MySQL Logger

### ISSUE THREAD

**Issue by javibrq** [MutonUfoAI/pgina#66]
Hello,

No data is writed on the mysql server (no event, no session) with pGina fork 3.9.9.7. Test ok. 
With pGina 3.1.8.0 it works fine on the same machine (W7x64) and same server

**Comment by MutonUfoAI** [comment]
Does work.
Please read http://mutonufoai.github.io/pgina/documentation/user.html#how_pgina_works
Only "pgina users" are going trough the pgina chain. If you log in with a local (administrator) or domain account no plugin is called.
