### ISSUE TITLE
macOS RDP -> W7 LDAP?

### ISSUE THREAD

**Issue by RAFd3v** [MutonUfoAI/pgina#67]
Is there a way to connect from

macOS Windows RDP to Win7 Ult machine with the pgina.fork 3.9.9.7 installed on it?
LDAP server is running on macOS Server 10.12.
I always get 

Anmeldung fehlschlagen: Der Benutzer besitzt nicht den benötigten Anmeldetyp aus diesem Computer.

Google Translate:
Logon Failure: The user does not have the required logon type from that computer.

**Comment by MutonUfoAI** [comment]
Logs are stored at %ProgramFiles%\pGina.fork\log
The eventlog will help  you too.
Its possible to rdp into a pgina machine
