### ISSUE TITLE
install with /silent asks for reboot

### ISSUE THREAD

**Issue by bjarnek** [MutonUfoAI/pgina#68]
I'm trying to install using a puppet manifest. 

Everything seems to be okay and after install i can exec a .reg file with my settings no problem.

However when installing i'm using /silent which still asks for a reboot yes/no dialog. I want to skip this portion and handle the reboot with the puppet "reboot" module instead after install. 

Tried the /verysilent option and this unfortunately just reboots without any regard for the rest of my puppet code. So i'm kind of stuck between an install that just reboots and disregards the rest of my puppet manifests or a single interaction from the user. 

Did i miss something obvious ? 

Also thanks for continuing to work on this nice piece of software ! :)

**Comment by MutonUfoAI** [comment]
pGinaSetup-....exe" /VERYSILENT /SP- /SUPPRESSMSGBOXES /NOCANCEL /NORESTART /RESTARTEXITCODE=3010 /LOG=%SystemDrive%\bla.log

its an inno setup
http://www.jrsoftware.org/ishelp/index.php?topic=setupcmdline

**Comment by bjarnek** [comment]
Fantastic!
Thanks for that amazing quick answer @MutonUfoAI
