### ISSUE TITLE
Domain Login overrides LDAP login

### ISSUE THREAD

**Issue by netprince17** [MutonUfoAI/pgina#70]
Thanks for your work with pgina fork...

I am trying to setup a computer lab on a university campus.  The computer lab will use the LDAP plugin to authenticate students against the university servers... (this works)

I also have the computers on our local active directory, so I can push configuration changes centrally...

The problem is that users in the active directory cant sign into the computers via LDAP.  It seems if the user has an account in our active directory, pgina fork will not check the LDAP credentials, even if the active directory credentials fail...

Is there a way to prevent pgina from trying to authenticate the user against our active directory?  Ideally I would only authenticate local accounts (for admin access) and LDAP users...

Thanks!

**Comment by MutonUfoAI** [comment]
use
.\username

**Comment by netprince17** [comment]
Yes that works... but my user base is pretty non-technical, so it will also cause a lot of problems.  Nobody thinks to type .\ before their username, and even if I post signs and details, only half of my users will read them...

**Comment by MutonUfoAI** [comment]
I can possible add another setting to reverse this behavior.
On Friday i'll take a look into it....

**Comment by netprince17** [comment]
That would be great... thanks.

**Comment by MutonUfoAI** [comment]
https://github.com/MutonUfoAI/pgina/releases

**Comment by netprince17** [comment]
thanks!  I will give it a try.

**Comment by netprince17** [comment]
The new option works perfectly for us, thanks!
