### ISSUE TITLE
Removing LDAP plugin settings

### ISSUE THREAD

**Issue by sambengtson** [MutonUfoAI/pgina#71]
Hello, 

I've recently configured the LDAP plugin and it is working great.  I'm now at a point where I would like to remove the plugin on a particular machine and switch to local machine auth.  However,  no matter what I do, it seems that pgina attempts LDAP auth.

I've gone as far as un-installing and re-installing pgina.  I can clearly see that the LDAP plugin should not be loaded as  authentication, authorize, and gateway options are not selected.

Any thoughts or ways that I can troubleshoot?  Thanks and great work on the project.

**Comment by sambengtson** [comment]
FYI this is a low priority.  Just something I ran across

**Comment by MutonUfoAI** [comment]
There is a log file
http://mutonufoai.github.io/pgina/documentation/user.html#logging
