### ISSUE TITLE
pgina to use for 2FA? 

### ISSUE THREAD

**Issue by neb382** [MutonUfoAI/pgina#74]
Hi all, i am looking for a solution to use Azure 2FA and need a CP for that. 
Unfortunately pgina is authenticate the use vs domain and therefore not running through radius plugin. 
Is there anyway to configure to use radius plugin first? than authenticate against domain? 

thx neb

**Comment by MutonUfoAI** [comment]
no support in pgina for 2FA

**Comment by neb382** [comment]
thx, for quick answer!!

**Comment by neb382** [comment]
do you know any other CP which may help supporting it? :)

**Comment by MutonUfoAI** [comment]
no
