### ISSUE TITLE
Terminal Server - Best practise

### ISSUE THREAD

**Issue by schwoerertw** [MutonUfoAI/pgina#79]
Hello,

first thank you for this great piece of software.

I am using pGina-Fork to implement 2FA authentification on a Windows Terminal Server(2012) against radius + ad (through radius) . I made two sourcecode changes(we use Logins in the Form:
User: Username without domain
PW: AD Passwort + 6 digit TOTP(Concatenated)

Changes:

- Radius Plugin cutting last 6 chars from Password after Radius-Auth OK and before WinApi call) and set the Domain.

- Change in the pgina Credential Provider just to stop authetication if @ oder \ is found in the username to stop authentication success without needing to concat 2FA token when username is given in the Form user@domain or domain\user.

Works like a charm, except for disconnected sessions already logged in to the terminal server. If the session is disconnected and the user tries to relogin via rdp authentication stops working (Bad Password) until I manually clear the disconnected session.

PGina log shows 

pGina.Service.Impl: User:xyz is Locked in Session:2

Any hints how i can stop pgIna from doing this and do a "normal" (same as initial) auth for disconnected RDP sessions?

**Comment by Opvolger** [comment]
I Think this will fix it:
https://github.com/MutonUfoAI/pgina/pull/80

**Comment by MutonUfoAI** [comment]
You mess around with the password, and expect pgina to magically know when to strip the last 6 chars from the pwd?

https://github.com/MutonUfoAI/pgina/blob/d1a36b71c757652fc4a84281c4ffa003afbc8911/pGina/src/Service/Impl/Service.cs#L450
add this
`
sessionDriver.UserInformation.Password = sessionDriver.UserInformation.Password.Substring(0, sessionDriver.UserInformation.Password.Length - 6)
`

**Comment by schwoerertw** [comment]
Hi,

i din't epxect pgina to do this magically and was totally aware that the lack of my understanding of the whole code right now and my changes caused this ;-). Anyway, thanks a lot for your fast reply, I will implement this at production ASAP and give feedback.

At the moment terminal sessions are set to terminate when disconnected.

Are there any plans to implement a setting to disable "plain" domain logins passing by pgina chain in the near future? My "fix" for that is, to speak carefully , not optimal ;) at the moment.

**Comment by MutonUfoAI** [comment]
This was no offense, im simply straightforward.

My suggestion is not guaranteed to work. I dont know your changes ...
And what you have disabled is there for a reason, to auth even domain users without using another credential provider.

If i where you, i would use another text field on the login screen and add those 6 digits there.
But that is a lot of work with a good amount of knowledge needed related to pgina and windows credential provider. I even think that pgina isnt a good fit for your needs.

**Comment by schwoerertw** [comment]
Didn't feel like an offense but i know the feeling of sombody without sufficient knowledge messing with my work and then crying for help afterwards ;-)

I realized myself pgina isn't a perfect fit for my needs, but I am not aware of an open source solution wchich gets nearer to them.

But I think generally it is more easy for me in the near future trying to dig deeper in your fork and change the source to my needs than any other open source solution i am aware of... The software is used by schools an they are lacking the budget for a commercial Out-Of-The-Box solution.

Changing the Radius plugin to present an additional field for the OTP pin would be nice to have, but users are used to concat the pw, so no show stopper at the moment.

For the Domain Logins, i fully understand the intention to make logins possible for domain joined machines without anotehr credential provider, but do you see any disadvantages in disabling this functionallity on demand/configuration? As a quick fix, before I can free some time to do some clean changes I changed the code to search for @ and/or \ in the Username and set the Username to a non existing one if found. *duck*

**Comment by schwoerertw** [comment]
Had some time to look through the code a little bit today, not already testet your solution. As far as I understand now, your change would cut the last 6 digits for rdp reconnects (user exists in pgina service) and forward to AD/local sam auth. This way, I loose the 2nd factor for all sessions only disconnected in RDP but still logged in if the user gives password and ANY 6 digits more.

I looked at the code changes Opvolger mentioned (#80) and this seems to be a good starting point for me, as it seems that the resulting code can be changed with little effort to bypass/deny the pure local SAM / AD verification and process the plugindriver /pluginchain again (Service.cs around line 500-600).

**Comment by schwoerertw** [comment]
Implemented the changes from Opvolger. Gave an internal error (Null reference) on relogin to a disconnected session (Domain User, AUTH trough radius plug). I will comment the change to get rid of the internal error in the pull req #80.
