### ISSUE TITLE
Windows 10 Creator Update

### ISSUE THREAD

**Issue by mdsystems** [MutonUfoAI/pgina#89]
Two of my VMs was updated to the Windows 10 Creator update recently. Now when I attempt to log in, the following message is displayed:

User xxxxx is Locked in session 1 but was not authenticated by pGina

Nothing has changed that I am aware of other than the update being installed.

I am able to see the local user and log in bypassing pGina but would ideally like to be using pGina again.

An extract from the log is attached.

[pGina.log](https://github.com/MutonUfoAI/pgina/files/1558458/pGina.log)

**Comment by MutonUfoAI** [comment]
2017-12-14 00:08:44,912 [2756|6|INFO ] pGina.Service.Impl: SessionChange:1 1
2017-12-14 00:08:44,947 [2756|34|INFO ] pGina.Service.Impl: SessionChange: 1 -> ConsoleConnect
2017-12-14 00:08:46,734 [2756|6|INFO ] pGina.Service.Impl: SessionChange:1 5
2017-12-14 00:08:46,752 [2756|35|INFO ] pGina.Service.Impl: SessionChange: 1 -> SessionLogon
2017-12-14 00:08:48,968 [2756|6|INFO ] pGina.Service.Impl: SessionChange:1 7
2017-12-14 00:08:49,036 [2756|36|INFO ] pGina.Service.Impl: SessionChange: 1 -> SessionLock
2017-12-14 00:38:52,614 [2756|29|INFO ] LocalMachine: LoginUserRequest() XXXXXX free to login
2017-12-14 00:38:52,706 [2756|29|ERROR] pGina.Service.Impl: User XXXXXX is Locked in Session 1 but was not authenticated by pGina. Unable to find SessionProperty in m_sessionPropertyCache.Get(1)

Thats a security precaution!
Pgina denies a logon attempt if this user is a "pgina user" and already logged in, and was not loged on by Pgina itself.
Most likely you need to re-configure the "Credential Provider Filter" setting
http://mutonufoai.github.io/pgina/documentation/user.html#credential_provider_filter

**Comment by mdsystems** [comment]
I appreciate that it may well be a security precaution. However, nothing has changed in the pGina configuration and this is from a clean boot before anyone has logged on. The user account in question was created by pGina, as you say. I am happy to take a look at the link, but it was working before the update and now does not.

How would the user have been logged on after a clean boot before anyone has logged into the computer?

**Comment by MutonUfoAI** [comment]
fast startup ?
https://www.tenforums.com/tutorials/4189-turn-off-fast-startup-windows-10-a.html
reg.exe add “HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Power” /v HiberbootEnabled /t REG_DWORD /d 0 /f

**Comment by mdsystems** [comment]
It's disabled as suggested but the problem persists. It does appear as though something is managing to log in prior to the actual pGina login, as if I attempt to close down the PC before logging in, it reports that other users are logged into the computer and may lose information.

**Comment by mdsystems** [comment]
I think it is fair to say that it is probably not pGina's fault here. There does appear to be something logging on as the user in question prior to an actual login. If I log in using pGina as another user, there is no issue. Something tells me that a startup service or something similar is using the user account at startup...

**Comment by MutonUfoAI** [comment]
https://www.tenforums.com/general-support/95776-restart-fall-creators-update-reopens-apps-before-9.html#post1177441

An application can use Application Recovery and Restart (ARR) to save data and state information before the application exits due to an unhandled exception or when the application stops responding. The application is also restarted, if requested.

It appears that for the Fall Creators Update Microsoft have chosen to boot this way when using Shut down or Restart from the Start Menu.

**Comment by mdsystems** [comment]
It does appear to be the case, yes. Thing is, even if no apps that interact with the UI are functioning, it still apparently logs on the user who was last logged in, which is what was causing the problem for me. I have just disabled the "feature" in Win10 as for me it works just fine. I have no need to have apps auto-restart in the VMs that I use.

Thanks for your assistance and for taking the time to comment.
