### ISSUE TITLE
Windows 10  - run as administrators - failed

### ISSUE THREAD

**Issue by demoli2** [MutonUfoAI/pgina#90]
Hello
Fresh install Windows 10 1709
Create 2 local accounts : 1 administrator + 1 user
With user account, it's possible to "run as administrators" all applications

But after install Pgina fork 3.9.9.10
Configuration => nothing (default config), reboot
It is impossible to launch a application with "run as administrators" on the user account.
system file error
I tried several configurations with Local Machine plugin.
Any ideas ?

**Comment by MutonUfoAI** [comment]
Windows 10 1709 bug.

**Comment by demoli2** [comment]
Why Windows 10 bug ?
If I uninstall pgina (and nothing else), it works well.
If I reinstall pgina (and nothing else), it impossible to use run as administrators

do you have an idea of a workaround ?

**Comment by demoli2** [comment]
I tested with the 1703 version of Windows 10 : a new computer out of the box.
I installed Pgina fork 3.9.9.10 and nothing else (default config).
It is impossible to launch applications with "run as administrators" on the user account. Not the same error :
"The extended attributes are inconsistent"

I think there is something wrong with the Local Machine Plugin but what ?

**Comment by demoli2** [comment]
Note :
With runas command, it works fine on all system 1703 and 1709 and with pgina installed. For example :
`runas /profile /user:local_name\login_admin cmd`

**Comment by MutonUfoAI** [comment]
https://github.com/MutonUfoAI/pgina/commit/b3d40eac7a4a5c966bca589cf847a82392c18378

**Comment by demoli2** [comment]
It works fine when I disable Cred UI for PGinaCredentialProvider (Credential Provider Options)
But I do not know the consequences of this deactivation...

**Comment by MutonUfoAI** [comment]
You cant use pgina for runas.
The next release will fix that
