### ISSUE TITLE
LDAP authentication issue with Pgina 3.9.9.10

### ISSUE THREAD

**Issue by rwpucko** [MutonUfoAI/pgina#91]
Hi Hans, 

Hope all is well. I've upgraded our lab image to use 3.9.9.10 from 3.9.9.4. Now when attempting to log in (authenticated via LDAP and then logged into domain user) I get the following error.

"The provided account:<my user name> name does not exist on:<our domain> or the password is wrong."

I checked to ensure the configuration is the same as the old system and everything looks good. Using my username i'm able to log into a lab computer using version 3.9.9.4, but not with .10. 

We are using Windows 10 LTSB 1603. 

Thanks for any help you can provide, 

Bob

**Comment by MutonUfoAI** [comment]
related ?
https://github.com/MutonUfoAI/pgina/issues/70
https://github.com/MutonUfoAI/pgina/releases/tag/3.9.9.5
http://mutonufoai.github.io/pgina/documentation/user.html#configuration
Logon options

**Comment by joshland** [comment]
I have the same issue.  pGina seems to generate no traffic at all (to the ldap server)

I have downgraded to 3.9.9.5.  I am now getting traffic.
