### ISSUE TITLE
Keeping some profiles/accounts local after logging out

### ISSUE THREAD

**Issue by mounte** [MutonUfoAI/pgina#92]
First huge thanks for this fork.

My question is related to the option: "Remove account and profile after logout"
As I understand there is some profile meta-data added to the profile description "pGina created" telling which accounts to delete.
In my setup I would like to have multiple classes of users.
1) Accounts from LDAP and/or RADIUS should keep their local accounts after logging out
2) Accounts from email-based login should be deleted after logging out

How would you go about this?
(The use case is a location with some public pc:s where we would like to allow members login easily using their member email. Other users accessing the same computers are "regulars" or workers who can keep their files in the local profile folder.
Therefor it would be great to delete all profiles by default but have exceptions on accounts coming from a certain plug-in or similar)

**Comment by MutonUfoAI** [comment]
I'm working on the [Scripting Plugin](http://mutonufoai.github.io/pgina/documentation/plugins/scripting.html) to extend is functionality, based on this [issue](https://github.com/MutonUfoAI/pgina/issues/88).
I can extend it even further, to include the GUID's for Authentication Authorization and Gateway.

You than can add a script or program to be called at logoff (system context) and do whatever you want.
A side note: If you run windows 8 or 10 you than need to disable Fast Startup
reg.exe add “HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Power” /v HiberbootEnabled /t REG_DWORD /d 0 /f
