### ISSUE TITLE
Application Safety

### ISSUE THREAD

**Issue by semzor** [MutonUfoAI/pgina#93]
Hello,

I don't know if this is the right place to ask but I've gone through the documentation, faq and also looked for it on the internet but couldn't find anything.
I am planning to use pgina-fork in a school lab environment. Is there any way to password protect the pGina.Configuration interface? I mean it is easily accessible and I am afraid students will get the radius secret, mysql password... etc.

**Comment by MutonUfoAI** [comment]
Only the user system and the administrators group is allowed to read pgina registry.
Passwords are encrypted but can easily be decrypted.
