### ISSUE TITLE
RDP Connection with User of Domain Controller in Windows Server 2012 or Windows 10

### ISSUE THREAD

**Issue by AndresCas123** [MutonUfoAI/pgina#94]
Hi !

When I am trying to login with a user of domain controller, pGina throw this message: "the user has not been granted the requested logon type at this computer".

The LDAP plugin has configured the Authentication, Gateway( rule with add user to group "Remote Desktop Users" ) and General Information tabs. After trying to login I verify the user´s groups in the machine and the user was added to the group "Remote Desktop Users".

Details:
-> pGina.fork 3.9.9.7 installed.
-> In the logs I don't see any error event.
-> the logs show that the user was successfully added to the "Remote Desktop Users" group.

This behavior only happens on Windows Server 2012 and Windows 10, with other operative systems( Windows 7, Windows 8 and Windows Server 2008), it works fine.

Thanks.

**Comment by MutonUfoAI** [comment]
http://mutonufoai.github.io/pgina/documentation/plugins/ldap.html#gateway_options

**Comment by AndresCas123** [comment]
Hi! thanks for replying !!

this configuration work fine for local user, but for domain controller users doesn´t, am I correct?

I was executing some tests with local users and the groups were correctly mapped but when logging in with domain users, pGina created a local account and assigned the groups but when Pgina finishes the GetSerialization method Windows takes other account( I think so ).

It is important to clarify this behavior is only for Connections RDP in Windows 10 and Windows Server 2012 

Help me please!

Thanks...

**Comment by MutonUfoAI** [comment]
Please also read http://mutonufoai.github.io/pgina/documentation/user.html
pGina.Service.ServiceHost_log.txt
at %ProgramFiles%\pGina.fork\log
and you stop guessing
