### ISSUE TITLE
Email authentication 

### ISSUE THREAD

**Issue by FreemanKyle** [MutonUfoAI/pgina#99]
Until now I used version 3.9.9.4 with the Email Authentication plugin and it worked correctly.
Now I update to 3.9.9.10 with the same plugin I put the username of the mail (before the @), and it does not work because it says that it is not a domain user.
I can enter with local and domain users but not with the user of the Email plugin.
Any solution?
Thank you.

**Comment by MutonUfoAI** [comment]
user .\ before the username
or enable Prefer local Authentication
http://mutonufoai.github.io/pgina/documentation/user.html#configuration
